// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiNjRj96OI_KyflaZtYfqM7J7zqxUjM18',
    appId: '1:159137626273:web:67fec7fc47f2a1f76a18e0',
    messagingSenderId: '159137626273',
    projectId: 'test-bba0d',
    authDomain: 'test-bba0d.firebaseapp.com',
    storageBucket: 'test-bba0d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7_n3tUYyJ1tzOF6Cwmm1eEPAgox2K54c',
    appId: '1:159137626273:android:fa26970b2a6797756a18e0',
    messagingSenderId: '159137626273',
    projectId: 'test-bba0d',
    storageBucket: 'test-bba0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHFz9iiaLr_48JmAb1IQn-qKL0eBVaiws',
    appId: '1:159137626273:ios:e66a343eac2b4f756a18e0',
    messagingSenderId: '159137626273',
    projectId: 'test-bba0d',
    storageBucket: 'test-bba0d.appspot.com',
    iosBundleId: 'com.example.bookApp',
  );
}
